title: VV Friends
author: LxF77 and VV Friends
email: none@example.com
description: > # this means to ignore newlines until "baseurl:"
  VV Friends landing page for Hurriane Rescue and Relief.

twitter_username: LxF77
github_username:  vattay

sass:
    style: compressed
